# SPDX-License-Identifier: MIT
# Copyright (C) J. Neuschäfer

name: build
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          sudo apt-get update
          sudo apt-get install -y gcc-arm-linux-gnueabi
      - run: make
      - uses: actions/upload-artifact@v3
        with:
          name: monitor
          path: |
            src/bare-metal/monitor.elf
            src/bare-metal/monitor*.bin
